/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThanksRouteImport } from './routes/thanks'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SelfLoveMentoringRouteImport } from './routes/self-love-mentoring'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RetreatsRouteImport } from './routes/retreats'
import { Route as ResonanceReleaseRouteImport } from './routes/resonance-release'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as OfferingsRouteImport } from './routes/offerings'
import { Route as MeditationRouteImport } from './routes/meditation'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CrystalReikiRouteImport } from './routes/crystal-reiki'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CacaoCeremoniesRouteImport } from './routes/cacao-ceremonies'
import { Route as BreathYogaRouteImport } from './routes/breath-yoga'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminNewsletterRouteImport } from './routes/admin.newsletter'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicHooksMonthlyNewsletterRouteImport } from './routes/api/public/hooks/monthly-newsletter'

const ThanksRoute = ThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfLoveMentoringRoute = SelfLoveMentoringRouteImport.update({
  id: '/self-love-mentoring',
  path: '/self-love-mentoring',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RetreatsRoute = RetreatsRouteImport.update({
  id: '/retreats',
  path: '/retreats',
  getParentRoute: () => rootRouteImport,
} as any)
const ResonanceReleaseRoute = ResonanceReleaseRouteImport.update({
  id: '/resonance-release',
  path: '/resonance-release',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferingsRoute = OfferingsRouteImport.update({
  id: '/offerings',
  path: '/offerings',
  getParentRoute: () => rootRouteImport,
} as any)
const MeditationRoute = MeditationRouteImport.update({
  id: '/meditation',
  path: '/meditation',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CrystalReikiRoute = CrystalReikiRouteImport.update({
  id: '/crystal-reiki',
  path: '/crystal-reiki',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CacaoCeremoniesRoute = CacaoCeremoniesRouteImport.update({
  id: '/cacao-ceremonies',
  path: '/cacao-ceremonies',
  getParentRoute: () => rootRouteImport,
} as any)
const BreathYogaRoute = BreathYogaRouteImport.update({
  id: '/breath-yoga',
  path: '/breath-yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/admin/newsletter',
  path: '/admin/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMonthlyNewsletterRoute =
  ApiPublicHooksMonthlyNewsletterRouteImport.update({
    id: '/api/public/hooks/monthly-newsletter',
    path: '/api/public/hooks/monthly-newsletter',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/breath-yoga': typeof BreathYogaRoute
  '/cacao-ceremonies': typeof CacaoCeremoniesRoute
  '/contact': typeof ContactRoute
  '/crystal-reiki': typeof CrystalReikiRoute
  '/events': typeof EventsRoute
  '/meditation': typeof MeditationRoute
  '/offerings': typeof OfferingsRoute
  '/packages': typeof PackagesRoute
  '/quiz': typeof QuizRoute
  '/resonance-release': typeof ResonanceReleaseRoute
  '/retreats': typeof RetreatsRoute
  '/reviews': typeof ReviewsRoute
  '/self-love-mentoring': typeof SelfLoveMentoringRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thanks': typeof ThanksRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/api/public/hooks/monthly-newsletter': typeof ApiPublicHooksMonthlyNewsletterRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/breath-yoga': typeof BreathYogaRoute
  '/cacao-ceremonies': typeof CacaoCeremoniesRoute
  '/contact': typeof ContactRoute
  '/crystal-reiki': typeof CrystalReikiRoute
  '/events': typeof EventsRoute
  '/meditation': typeof MeditationRoute
  '/offerings': typeof OfferingsRoute
  '/packages': typeof PackagesRoute
  '/quiz': typeof QuizRoute
  '/resonance-release': typeof ResonanceReleaseRoute
  '/retreats': typeof RetreatsRoute
  '/reviews': typeof ReviewsRoute
  '/self-love-mentoring': typeof SelfLoveMentoringRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thanks': typeof ThanksRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/api/public/hooks/monthly-newsletter': typeof ApiPublicHooksMonthlyNewsletterRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/breath-yoga': typeof BreathYogaRoute
  '/cacao-ceremonies': typeof CacaoCeremoniesRoute
  '/contact': typeof ContactRoute
  '/crystal-reiki': typeof CrystalReikiRoute
  '/events': typeof EventsRoute
  '/meditation': typeof MeditationRoute
  '/offerings': typeof OfferingsRoute
  '/packages': typeof PackagesRoute
  '/quiz': typeof QuizRoute
  '/resonance-release': typeof ResonanceReleaseRoute
  '/retreats': typeof RetreatsRoute
  '/reviews': typeof ReviewsRoute
  '/self-love-mentoring': typeof SelfLoveMentoringRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thanks': typeof ThanksRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/api/public/hooks/monthly-newsletter': typeof ApiPublicHooksMonthlyNewsletterRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/breath-yoga'
    | '/cacao-ceremonies'
    | '/contact'
    | '/crystal-reiki'
    | '/events'
    | '/meditation'
    | '/offerings'
    | '/packages'
    | '/quiz'
    | '/resonance-release'
    | '/retreats'
    | '/reviews'
    | '/self-love-mentoring'
    | '/sitemap.xml'
    | '/thanks'
    | '/admin/newsletter'
    | '/api/public/hooks/monthly-newsletter'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/breath-yoga'
    | '/cacao-ceremonies'
    | '/contact'
    | '/crystal-reiki'
    | '/events'
    | '/meditation'
    | '/offerings'
    | '/packages'
    | '/quiz'
    | '/resonance-release'
    | '/retreats'
    | '/reviews'
    | '/self-love-mentoring'
    | '/sitemap.xml'
    | '/thanks'
    | '/admin/newsletter'
    | '/api/public/hooks/monthly-newsletter'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/breath-yoga'
    | '/cacao-ceremonies'
    | '/contact'
    | '/crystal-reiki'
    | '/events'
    | '/meditation'
    | '/offerings'
    | '/packages'
    | '/quiz'
    | '/resonance-release'
    | '/retreats'
    | '/reviews'
    | '/self-love-mentoring'
    | '/sitemap.xml'
    | '/thanks'
    | '/admin/newsletter'
    | '/api/public/hooks/monthly-newsletter'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  BreathYogaRoute: typeof BreathYogaRoute
  CacaoCeremoniesRoute: typeof CacaoCeremoniesRoute
  ContactRoute: typeof ContactRoute
  CrystalReikiRoute: typeof CrystalReikiRoute
  EventsRoute: typeof EventsRoute
  MeditationRoute: typeof MeditationRoute
  OfferingsRoute: typeof OfferingsRoute
  PackagesRoute: typeof PackagesRoute
  QuizRoute: typeof QuizRoute
  ResonanceReleaseRoute: typeof ResonanceReleaseRoute
  RetreatsRoute: typeof RetreatsRoute
  ReviewsRoute: typeof ReviewsRoute
  SelfLoveMentoringRoute: typeof SelfLoveMentoringRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ThanksRoute: typeof ThanksRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  ApiPublicHooksMonthlyNewsletterRoute: typeof ApiPublicHooksMonthlyNewsletterRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thanks': {
      id: '/thanks'
      path: '/thanks'
      fullPath: '/thanks'
      preLoaderRoute: typeof ThanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-love-mentoring': {
      id: '/self-love-mentoring'
      path: '/self-love-mentoring'
      fullPath: '/self-love-mentoring'
      preLoaderRoute: typeof SelfLoveMentoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retreats': {
      id: '/retreats'
      path: '/retreats'
      fullPath: '/retreats'
      preLoaderRoute: typeof RetreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resonance-release': {
      id: '/resonance-release'
      path: '/resonance-release'
      fullPath: '/resonance-release'
      preLoaderRoute: typeof ResonanceReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offerings': {
      id: '/offerings'
      path: '/offerings'
      fullPath: '/offerings'
      preLoaderRoute: typeof OfferingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meditation': {
      id: '/meditation'
      path: '/meditation'
      fullPath: '/meditation'
      preLoaderRoute: typeof MeditationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crystal-reiki': {
      id: '/crystal-reiki'
      path: '/crystal-reiki'
      fullPath: '/crystal-reiki'
      preLoaderRoute: typeof CrystalReikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cacao-ceremonies': {
      id: '/cacao-ceremonies'
      path: '/cacao-ceremonies'
      fullPath: '/cacao-ceremonies'
      preLoaderRoute: typeof CacaoCeremoniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breath-yoga': {
      id: '/breath-yoga'
      path: '/breath-yoga'
      fullPath: '/breath-yoga'
      preLoaderRoute: typeof BreathYogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/admin/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/monthly-newsletter': {
      id: '/api/public/hooks/monthly-newsletter'
      path: '/api/public/hooks/monthly-newsletter'
      fullPath: '/api/public/hooks/monthly-newsletter'
      preLoaderRoute: typeof ApiPublicHooksMonthlyNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  BreathYogaRoute: BreathYogaRoute,
  CacaoCeremoniesRoute: CacaoCeremoniesRoute,
  ContactRoute: ContactRoute,
  CrystalReikiRoute: CrystalReikiRoute,
  EventsRoute: EventsRoute,
  MeditationRoute: MeditationRoute,
  OfferingsRoute: OfferingsRoute,
  PackagesRoute: PackagesRoute,
  QuizRoute: QuizRoute,
  ResonanceReleaseRoute: ResonanceReleaseRoute,
  RetreatsRoute: RetreatsRoute,
  ReviewsRoute: ReviewsRoute,
  SelfLoveMentoringRoute: SelfLoveMentoringRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ThanksRoute: ThanksRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  ApiPublicHooksMonthlyNewsletterRoute: ApiPublicHooksMonthlyNewsletterRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
